### ISSUE TITLE
Errors for executing "sh scripts/exe_post.sh"

### ISSUE THREAD

**Issue by chaochun** [lijierui/group-attention#1]
After repeated your example,
```
sh scripts/exe_post.sh out
```
the system has thrown errors as following.

```
Traceback (most recent call last):
  File "src/main.py", line 161, in <module>
    step_one()
  File "src/main.py", line 90, in step_one
    post_flag = args.post_flag)
  File "src/train/pre_seq2eq_trainer.py", line 327, in train
    post_flag = post_flag)
  File "src/train/pre_seq2eq_trainer.py", line 201, in _train_epoches
    post_flag = post_flag)
  File "src/train/pre_seq2eq_trainer.py", line 95, in _train_batch
    class_list = self.class_list)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "src/model/seq2seq.py", line 22, in forward
    encoder_outputs, encoder_hidden = self.encoder(input_variable, input_lengths)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "src/model/EncoderRNN.py", line 47, in forward
    src_mask = self.group_attention.get_mask(input_var)
  File "src/model/attention_1.py", line 158, in get_mask
    self.final = torch.cat((self.src_mask_between.cuda(),self.src_mask_self.cuda(),self.src_mask_global.cuda(),self.src_mask_question.cuda()),1)
RuntimeError: Expected object of scalar type Byte but got scalar type Bool for sequence element 2 in sequence argument at position #1 'tensors'
```

My environment is pytorch 1.2 and python 3.6.
Is any suggestion to fix it?

**Comment by lijierui** [comment]
Sorry for the late reply. I have no access to the server now and can't reproduce this bug. For those who might be encountered with the same problem. It seems there's a problem with the Tensor Type(Byte/Bool). I remember the PyTorch I'm using an older version. You can try 0.4.1 or 1.0.0. Or you can manually set all mask to be Byte tensors by
self.final = torch.cat((self.src_mask_between.cuda().byte(), self.src_mask_self.cuda().byte(), \
                       self.src_mask_global.cuda().byte(), self.src_mask_question.cuda().byte()),1)
Didn't try it though, hopefully this will work.
